[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.11", features = [], default-features = true }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"], default-features = false }
log = { version = "0.4.20", features = [], default-features = false }
env_logger = { version = "0.10.1", features = ["auto-color", "humantime"], default-features = false }
